name = "zzgcopilot-web"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "zzgcopilot-db"
database_id = "f51cd6bd-fcb0-47ce-90ca-32209552c7bf"

[[r2_buckets]]
binding = "R2"
bucket_name = "zzgcopilot-assets"

[vars]
NEXTAUTH_URL = "https://zzgcopilot.com"
