name = "zzgcopilot-web"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[[d1_databases]]
binding = "DB"
database_name = "zzgcopilot-db"
database_id = "6306be87-8b34-4573-8bc6-9202dd660785"

[[r2_buckets]]
binding = "R2"
bucket_name = "zzgcopilot-assets"

[vars]
NEXTAUTH_URL = "https://zzgcopilot.com"
