import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

test('homepage retains the existing visual shell while reading navigation from Sanity', () => {
  const home = read('src/app/page.tsx')
  assert.match(home, /getSanityNavigation/)
  assert.match(home, /getSanitySiteSettings/)
  assert.match(home, /site-home/)
  assert.match(read('src/app/globals.css'), /--site-surface, #f8f9fa/)
  assert.match(home, /settings\.homepageSectionTitle/)
  assert.match(home, /settings\.homepageCtaLabel/)
  assert.match(home, /getSanityPublishedPostCount/)
  assert.match(home, /getSanityCategories/)
  assert.match(home, /aria-label="教程分类"/)
  assert.match(home, /name="q"/)
  assert.match(home, /pageHref/)
})

test('unified Sanity settings center controls the homepage without changing its defaults', () => {
  const settings = read('sanity-studio/schemaTypes/siteSettingsType.ts')
  const content = read('src/lib/sanity-content.ts')
  const layout = read('src/app/layout.tsx')
  const home = read('src/app/page.tsx')
  const css = read('src/app/globals.css')
  assert.match(read('sanity-studio/structure.ts'), /网站设置中心/)
  for (const field of ['showHeaderSearch', 'showHeaderCta', 'showHomepageHero', 'homepageHeroTitle', 'homepageHeroDescription', 'homepageHeroImage', 'homepageHeroPrimaryLabel', 'homepageHeroSecondaryLabel', 'postsPerPage', 'homepageMaxWidth', 'cardColumns', 'cardGap', 'cardImageHeight', 'showCardCategory', 'showCardDate', 'showCardReadingTime', 'showFooter']) {
    assert.match(settings, new RegExp(`name: '${field}'`))
    assert.match(content, new RegExp(field))
  }
  assert.match(layout, /data-card-columns/)
  assert.match(home, /site-card-grid/)
  assert.match(home, /id="latest-tutorials"/)
  assert.match(css, /site-hero-orb/)
  assert.match(css, /prefers-reduced-motion/)
  assert.match(css, /--site-card-image-height/)
})

test('all public content routes use Sanity-only readers', () => {
  assert.match(read('src/app/tutorials/[slug]/page.tsx'), /getSanityPost/)
  assert.match(read('src/app/pages/[slug]/page.tsx'), /getSanityPage/)
  assert.match(read('src/app/api/posts/route.ts'), /getSanityPublishedPosts/)
  assert.match(read('src/app/api/sitemap/route.ts'), /getSanitySitemapEntries/)
  assert.doesNotMatch(read('src/lib/sanity-content.ts'), /view_count|getDb|getR2/)
})

test('lightweight editor keeps SEO, design, redirects, and public tutorials', () => {
  const settings = read('sanity-studio/schemaTypes/siteSettingsType.ts')
  const post = read('sanity-studio/schemaTypes/postType.ts')
  const config = read('sanity-studio/sanity.config.ts')
  assert.match(settings, /primaryColor/)
  assert.doesNotMatch(settings, /commentsEnabled|membershipEnabled|paidContentEnabled|analyticsEnabled/)
  assert.doesNotMatch(post, /accessLevel|stripePriceId|commentsEnabled/)
  assert.match(post, /seoFields/)
  assert.match(config, /FeatureCenter/)
  assert.match(read('sanity-studio/schemaTypes/redirectType.ts'), /sourcePath/)
  assert.doesNotMatch(read('src/app/layout.tsx'), /AnalyticsBeacon/)
  assert.doesNotMatch(read('src/app/page.tsx'), /ContactForm/)
})

test('controlled theme and template center provides safe one-click presets without third-party code execution', () => {
  const center = read('sanity-studio/components/ThemeTemplateCenter.tsx')
  const settings = read('sanity-studio/schemaTypes/siteSettingsType.ts')
  const layout = read('src/app/layout.tsx')
  const home = read('src/app/page.tsx')
  assert.match(center, /经典教程/)
  assert.match(center, /极简蓝白/)
  assert.match(center, /暖色杂志/)
  assert.match(center, /森林知识库/)
  assert.match(center, /安装为新草稿/)
  assert.match(center, /status: 'draft'/)
  assert.match(center, /client\.patch\('site-settings'\)/)
  assert.doesNotMatch(center, /eval\(|new Function|npm install/)
  assert.match(settings, /name: 'themePreset'/)
  assert.match(settings, /name: 'cardStyle'/)
  assert.match(layout, /data-site-theme/)
  assert.match(home, /site-card/)
})

test('template, module, and content-model centers provide reversible no-code operations', () => {
  const themes = read('sanity-studio/components/ThemeTemplateCenter.tsx')
  const features = read('sanity-studio/components/FeatureCenter.tsx')
  const models = read('sanity-studio/components/ContentModelCenter.tsx')
  const settings = read('sanity-studio/schemaTypes/siteSettingsType.ts')
  const article = read('src/app/tutorials/[slug]/page.tsx')
  const config = read('sanity-studio/sanity.config.ts')
  assert.match(themes, /themeBackup/)
  assert.match(themes, /撤销上次更换/)
  assert.match(themes, /cardColumns/)
  assert.match(features, /推荐博客功能包/)
  assert.match(features, /client\.patch\('site-settings'\)/)
  assert.match(models, /分步教程/)
  assert.match(models, /课程章节/)
  assert.match(models, /产品评测/)
  assert.match(models, /常见问题页面/)
  assert.match(config, /ContentModelCenter/)
  assert.match(settings, /shareButtonsEnabled/)
  assert.match(settings, /relatedPostsEnabled/)
  assert.match(article, /ArticleEnhancements/)
  assert.match(article, /相关文章/)
  assert.match(article, /getSanityRelatedPosts/)
  assert.doesNotMatch(features, /eval\(|new Function|npm install/)
})

test('visual page designer, dynamic fields, and side-by-side template comparison are wired end to end', () => {
  const designer = read('sanity-studio/components/PageDesignerCenter.tsx')
  const fieldDefinition = read('sanity-studio/schemaTypes/customFieldDefinitionType.ts')
  const fieldInput = read('sanity-studio/components/CustomFieldsInput.tsx')
  const comparison = read('sanity-studio/components/TemplateComparisonCenter.tsx')
  const bridge = read('src/components/TemplatePreviewBridge.tsx')
  const content = read('src/lib/sanity-content.ts')
  const visualSections = read('src/components/VisualSections.tsx')
  assert.match(designer, /draggable/)
  assert.match(designer, /onDrop/)
  assert.match(designer, /保存并应用/)
  assert.match(visualSections, /section\.hidden/)
  assert.match(fieldDefinition, /fieldType/)
  assert.match(fieldDefinition, /displayOnPage/)
  assert.match(fieldInput, /customFieldDefinition/)
  assert.match(content, /customFieldsProjection/)
  assert.match(comparison, /当前网站/)
  assert.match(comparison, /候选模板/)
  assert.match(comparison, /iframe/)
  assert.match(bridge, /templatePreview/)
  assert.doesNotMatch(designer + fieldInput + comparison, /eval\(|new Function|dangerouslySetInnerHTML/)
})

test('controlled plugin and block marketplaces include permissions, audit, rollback, and safe renderers', () => {
  const features = read('sanity-studio/components/FeatureCenter.tsx')
  const settings = read('sanity-studio/schemaTypes/siteSettingsType.ts')
  const audit = read('sanity-studio/schemaTypes/pluginAuditType.ts')
  const sections = read('sanity-studio/schemaTypes/pageSections.ts')
  const designer = read('sanity-studio/components/PageDesignerCenter.tsx')
  const renderer = read('src/components/VisualSections.tsx')
  assert.match(features, /useCurrentUser/)
  assert.match(features, /permissions/)
  assert.match(features, /回滚上次操作/)
  assert.match(features, /更新版本/)
  assert.match(features, /pluginAudit/)
  assert.match(settings, /pluginInstallations/)
  assert.match(audit, /actorName/)
  assert.match(designer, /区块市场/)
  for (const type of ['featureGrid', 'statsGrid', 'testimonialGrid', 'pricingTable', 'dividerBlock']) {
    assert.match(sections, new RegExp(type))
    assert.match(renderer, new RegExp(type))
  }
  assert.doesNotMatch(features + designer + renderer, /eval\(|new Function|dangerouslySetInnerHTML|npm install/)
})

test('service connection center reports readiness without returning secret values', () => {
  const center = read('sanity-studio/components/ServiceConnectionCenter.tsx')
  const route = read('src/app/api/integrations/status/route.ts')
  const config = read('sanity-studio/sanity.config.ts')
  assert.match(center, /服务连接/)
  assert.match(center, /不会读取或展示密钥内容/)
  assert.match(center, /api\/integrations\/status/)
  assert.match(config, /ServiceConnectionCenter/)
  assert.match(route, /Boolean\(platformValue/)
  assert.match(route, /Cache-Control.*no-store/)
  assert.doesNotMatch(route, /get-secret-value|secret\s*:/i)
})

test('lightweight runtime removes D1 and R2 bindings while retaining Sanity backups in Vercel Blob', () => {
  const wrangler = read('wrangler.toml')
  const ci = read('.gitlab-ci.yml')
  assert.doesNotMatch(wrangler, /\[\[d1_databases\]\]|\[\[r2_buckets\]\]/)
  assert.doesNotMatch(ci, /migrate_production_db|d1 migrations apply/)
  assert.match(ci, /monthly_sanity_backup/)
  assert.match(ci, /deploy_sanity_studio/)
  assert.match(read('package.json'), /backup:sanity/)
  assert.match(read('scripts/backup-sanity.sh'), /backup-sanity-assets/)
  assert.match(read('scripts/backup-sanity.sh'), /upload-backup-to-vercel-blob/)
  assert.doesNotMatch(read('scripts/backup-sanity.sh'), /wrangler\s+r2/)
  assert.doesNotMatch(read('src/app/tutorials/[slug]/page.tsx'), /Comments|CheckoutButton|currentMember|platformDb/)
})

test('Sanity revalidation is signed and invalidates narrow content tags', () => {
  const route = read('src/app/api/revalidate/route.ts')
  const content = read('src/lib/sanity-content.ts')
  assert.match(route, /x-sanity-revalidate-secret/)
  assert.match(route, /revalidateTag\(tag, 'max'\)/)
  assert.match(route, /sanity:post:/)
  assert.match(content, /next: \{ revalidate: 60, tags \}/)
})

test('production CI deploys after validation without a D1 migration stage', () => {
  const ci = read('.gitlab-ci.yml')
  assert.match(ci, /deploy_sanity_studio:/)
  assert.match(ci, /needs: \["validate"\]/)
  assert.doesNotMatch(ci, /deploy_cloudflare_pages|pages\.dev|wrangler pages deploy/)
  assert.doesNotMatch(ci, /migrate_production_db|d1 migrations apply/)
})

test('legacy admin and account entry points are retired in favor of Sanity Studio', () => {
  const middleware = read('src/middleware.ts')
  assert.match(middleware, /SANITY_STUDIO_URL/)
  assert.match(middleware, /pathname\.startsWith\('\/admin'\)/)
  assert.match(middleware, /pathname === '\/login'/)
  assert.match(middleware, /pathname\.startsWith\('\/api\/admin'\)/)
  assert.match(middleware, /status: 410/)
  assert.doesNotMatch(middleware, /pathname\.startsWith\('\/uploads'\)/)
})

test('Sanity schemas own posts, settings, and image assets', () => {
  const post = read('sanity-studio/schemaTypes/postType.ts')
  const settings = read('sanity-studio/schemaTypes/siteSettingsType.ts')
  assert.match(post, /name: 'coverImage'/)
  assert.match(post, /type: 'image'/)
  assert.match(post, /portableTextField/)
  assert.match(post, /value: 'scheduled'/)
  assert.match(post, /name: 'editorialStage'/)
  assert.match(settings, /name: 'defaultCoverImage'/)
  assert.match(settings, /type: 'image'/)
  assert.match(settings, /name: 'homepageSectionTitle'/)
  assert.match(settings, /name: 'homepageFooterNote'/)
})

test('SEO uses a public sitemap and article recommendations prefer dynamic Sanity content', () => {
  const content = read('src/lib/sanity-content.ts')
  const sitemap = read('src/app/sitemap.ts')
  const article = read('src/app/tutorials/[slug]/page.tsx')
  assert.match(sitemap, /getSanitySitemapEntries/)
  assert.match(sitemap, /changeFrequency/)
  assert.match(content, /getSanityRelatedPosts/)
  assert.match(content, /sameCategory/)
  assert.match(article, /articleSection/)
  assert.match(article, /keywords/)
})

test('homepage uses a 4 by 4 page and automatically groups Microsoft tutorials', () => {
  const homepage = read('src/app/page.tsx')
  const content = read('src/lib/sanity-content.ts')
  const css = read('src/app/globals.css')
  const settings = read('sanity-studio/schemaTypes/siteSettingsType.ts')
  const importer = read('sanity-studio/scripts/import-word-tutorial-html.mjs')
  assert.match(homepage, /lg:grid-cols-4/)
  assert.match(homepage, /settings\.postsPerPage \|\| 16/)
  assert.match(settings, /initialValue: 16/)
  assert.match(settings, /4 列 × 4 行/)
  assert.match(settings, /name: 'cardColumns'.*initialValue: 4/)
  assert.match(importer, /postsPerPage: 16/)
  assert.match(content, /MICROSOFT_CATEGORY_NAME = '微软办公软件'/)
  assert.match(content, /MICROSOFT_CATEGORY_SLUG = 'microsoft-office'/)
  assert.match(css, /aspect-ratio: 330 \/ 302/)
  assert.match(css, /aspect-ratio: 16 \/ 9/)
  assert.match(homepage, /line-clamp-2 text-\[16px\]/)
  assert.doesNotMatch(homepage, /min-h-\[220px\]/)
  for (const product of ['Word', 'Excel', 'PowerPoint', 'Microsoft 365', 'Microsoft Teams']) {
    assert.match(content, new RegExp(product))
  }
  assert.match(content, /pt::text\(body\) match/)
})

test('WordPress-style editing tools include media, preview, scheduling, and review queues', () => {
  const config = read('sanity-studio/sanity.config.ts')
  const structure = read('sanity-studio/structure.ts')
  const portableText = read('sanity-studio/schemaTypes/portableText.ts')
  const publicContent = read('src/lib/sanity-content.ts')
  assert.match(config, /media\(/)
  assert.match(config, /presentationTool/)
  assert.match(config, /SubmitForReviewAction/)
  assert.match(structure, /ContentPreview/)
  assert.match(structure, /待审核/)
  assert.match(structure, /计划发布/)
  assert.match(portableText, /提示框/)
  assert.match(portableText, /操作步骤/)
  assert.match(portableText, /下载按钮/)
  assert.match(publicContent, /status == "scheduled"/)
  assert.match(publicContent, /dateTime\(publishedAt\) <= dateTime\(now\(\)\)/)
  assert.match(publicContent, /expiresAt/)
  assert.match(read('sanity-studio/actions/editorialActions.tsx'), /hasApprovalRole/)
  assert.match(read('src/app/api/draft-mode/enable/route.ts'), /validatePreviewUrl/)
})

test('recovery backups include drafts, published documents, and image binaries', () => {
  const backup = read('scripts/backup-sanity.sh')
  assert.match(backup, /export-sanity-content\.mjs/)
  assert.match(backup, /backup-sanity-assets\.mjs/)
  assert.match(backup, /upload-backup-to-vercel-blob\.mjs/)
  assert.match(read('scripts/backup-sanity-assets.mjs'), /cdn\.sanity\.io/)
  assert.match(read('scripts/backup-sanity-assets.mjs'), /bodyAssets/)
  assert.match(read('scripts/export-sanity-content.mjs'), /perspective', 'raw'/)
  assert.match(read('scripts/export-sanity-content.mjs'), /SANITY_AUTH_TOKEN/)
  const backupWorkflow = read('.github/workflows/monthly-vercel-blob-backup.yml')
  assert.match(backupWorkflow, /SANITY_BACKUP_TOKEN/)
  assert.match(backupWorkflow, /VERCEL_BLOB_READ_WRITE_TOKEN/)
  assert.doesNotMatch(backupWorkflow, /CLOUDFLARE_API_TOKEN/)
})
