import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

test('homepage retains the existing visual shell while reading navigation from Sanity', () => {
  const home = read('src/app/page.tsx')
  assert.match(home, /getSanityNavigation/)
  assert.match(home, /getSanitySiteSettings/)
  assert.match(home, /site-home/)
  assert.match(read('src/app/globals.css'), /--site-surface, #f8f9fa/)
  assert.match(home, /settings\.homepageSectionTitle/)
  assert.match(home, /settings\.homepageCtaLabel/)
  assert.match(home, /getSanityPublishedPostCount/)
  assert.match(home, /name="q"/)
  assert.match(home, /pageHref/)
})

test('all public content routes use Sanity-only readers', () => {
  assert.match(read('src/app/tutorials/[slug]/page.tsx'), /getSanityPost/)
  assert.match(read('src/app/pages/[slug]/page.tsx'), /getSanityPage/)
  assert.match(read('src/app/api/posts/route.ts'), /getSanityPublishedPosts/)
  assert.match(read('src/app/api/sitemap/route.ts'), /getSanitySitemapEntries/)
  assert.doesNotMatch(read('src/lib/sanity-content.ts'), /view_count|getDb|getR2/)
})

test('extended editor experience covers SEO, design, redirects, engagement, and gated content', () => {
  const settings = read('sanity-studio/schemaTypes/siteSettingsType.ts')
  const post = read('sanity-studio/schemaTypes/postType.ts')
  const config = read('sanity-studio/sanity.config.ts')
  assert.match(settings, /primaryColor/)
  assert.match(settings, /commentsEnabled/)
  assert.match(settings, /membershipEnabled/)
  assert.match(post, /accessLevel/)
  assert.match(post, /seoFields/)
  assert.match(config, /FeatureCenter/)
  assert.match(read('sanity-studio/schemaTypes/redirectType.ts'), /sourcePath/)
  assert.match(read('migrations/0005_engagement_membership.sql'), /analytics_daily/)
  assert.match(read('src/lib/platform.ts'), /TURNSTILE_SECRET_KEY/)
})

test('controlled theme and template center provides safe one-click presets without third-party code execution', () => {
  const center = read('sanity-studio/components/ThemeTemplateCenter.tsx')
  const settings = read('sanity-studio/schemaTypes/siteSettingsType.ts')
  const layout = read('src/app/layout.tsx')
  const home = read('src/app/page.tsx')
  assert.match(center, /经典教程/)
  assert.match(center, /极简蓝白/)
  assert.match(center, /暖色杂志/)
  assert.match(center, /森林知识库/)
  assert.match(center, /安装为新草稿/)
  assert.match(center, /status: 'draft'/)
  assert.match(center, /client\.patch\('site-settings'\)/)
  assert.doesNotMatch(center, /eval\(|new Function|npm install/)
  assert.match(settings, /name: 'themePreset'/)
  assert.match(settings, /name: 'cardStyle'/)
  assert.match(layout, /data-site-theme/)
  assert.match(home, /site-card/)
})

test('legacy admin and account entry points are retired in favor of Sanity Studio', () => {
  const middleware = read('src/middleware.ts')
  assert.match(middleware, /SANITY_STUDIO_URL/)
  assert.match(middleware, /pathname\.startsWith\('\/admin'\)/)
  assert.match(middleware, /pathname === '\/login'/)
  assert.match(middleware, /pathname\.startsWith\('\/api\/admin'\)/)
  assert.match(middleware, /status: 410/)
  assert.doesNotMatch(middleware, /pathname\.startsWith\('\/uploads'\)/)
})

test('Sanity schemas own posts, settings, and image assets', () => {
  const post = read('sanity-studio/schemaTypes/postType.ts')
  const settings = read('sanity-studio/schemaTypes/siteSettingsType.ts')
  assert.match(post, /name: 'coverImage'/)
  assert.match(post, /type: 'image'/)
  assert.match(post, /portableTextField/)
  assert.match(post, /value: 'scheduled'/)
  assert.match(post, /name: 'editorialStage'/)
  assert.match(settings, /name: 'defaultCoverImage'/)
  assert.match(settings, /type: 'image'/)
  assert.match(settings, /name: 'homepageSectionTitle'/)
  assert.match(settings, /name: 'homepageFooterNote'/)
})

test('WordPress-style editing tools include media, preview, scheduling, and review queues', () => {
  const config = read('sanity-studio/sanity.config.ts')
  const structure = read('sanity-studio/structure.ts')
  const portableText = read('sanity-studio/schemaTypes/portableText.ts')
  const publicContent = read('src/lib/sanity-content.ts')
  assert.match(config, /media\(/)
  assert.match(config, /presentationTool/)
  assert.match(config, /SubmitForReviewAction/)
  assert.match(structure, /ContentPreview/)
  assert.match(structure, /待审核/)
  assert.match(structure, /计划发布/)
  assert.match(portableText, /提示框/)
  assert.match(portableText, /操作步骤/)
  assert.match(portableText, /下载按钮/)
  assert.match(publicContent, /status == "scheduled"/)
  assert.match(publicContent, /dateTime\(publishedAt\) <= dateTime\(now\(\)\)/)
  assert.match(publicContent, /expiresAt/)
  assert.match(read('sanity-studio/actions/editorialActions.tsx'), /hasApprovalRole/)
  assert.match(read('src/app/api/draft-mode/enable/route.ts'), /validatePreviewUrl/)
})

test('recovery backups include drafts, published documents, and image binaries', () => {
  const backup = read('scripts/backup-cloudflare.sh')
  assert.match(backup, /export-sanity-content\.mjs/)
  assert.match(backup, /backup-sanity-assets\.mjs/)
  assert.match(read('scripts/backup-sanity-assets.mjs'), /cdn\.sanity\.io/)
  assert.match(read('scripts/backup-sanity-assets.mjs'), /bodyAssets/)
  assert.match(read('scripts/export-sanity-content.mjs'), /perspective', 'raw'/)
  assert.match(read('scripts/export-sanity-content.mjs'), /SANITY_AUTH_TOKEN/)
  assert.match(read('.github/workflows/monthly-cloudflare-backup.yml'), /SANITY_BACKUP_TOKEN/)
})
