import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

test('homepage retains the existing visual shell while reading navigation from Sanity', () => {
  const home = read('src/app/page.tsx')
  assert.match(home, /getSanityNavigation/)
  assert.match(home, /getSanitySiteSettings/)
  assert.match(home, /site-home/)
  assert.match(read('src/app/globals.css'), /--site-surface, #f8f9fa/)
  assert.match(home, /settings\.homepageSectionTitle/)
  assert.match(home, /settings\.homepageCtaLabel/)
  assert.match(home, /getSanityPublishedPostCount/)
  assert.match(home, /name="q"/)
  assert.match(home, /pageHref/)
})

test('unified Sanity settings center controls the homepage without changing its defaults', () => {
  const settings = read('sanity-studio/schemaTypes/siteSettingsType.ts')
  const content = read('src/lib/sanity-content.ts')
  const layout = read('src/app/layout.tsx')
  const home = read('src/app/page.tsx')
  const css = read('src/app/globals.css')
  assert.match(read('sanity-studio/structure.ts'), /网站设置中心/)
  for (const field of ['showHeaderSearch', 'showHeaderCta', 'postsPerPage', 'homepageMaxWidth', 'cardColumns', 'cardGap', 'cardImageHeight', 'showCardCategory', 'showCardDate', 'showCardReadingTime', 'showFooter']) {
    assert.match(settings, new RegExp(`name: '${field}'`))
    assert.match(content, new RegExp(field))
  }
  assert.match(layout, /data-card-columns/)
  assert.match(home, /site-card-grid/)
  assert.match(css, /--site-card-image-height/)
})

test('all public content routes use Sanity-only readers', () => {
  assert.match(read('src/app/tutorials/[slug]/page.tsx'), /getSanityPost/)
  assert.match(read('src/app/pages/[slug]/page.tsx'), /getSanityPage/)
  assert.match(read('src/app/api/posts/route.ts'), /getSanityPublishedPosts/)
  assert.match(read('src/app/api/sitemap/route.ts'), /getSanitySitemapEntries/)
  assert.doesNotMatch(read('src/lib/sanity-content.ts'), /view_count|getDb|getR2/)
})

test('extended editor experience covers SEO, design, redirects, engagement, and gated content', () => {
  const settings = read('sanity-studio/schemaTypes/siteSettingsType.ts')
  const post = read('sanity-studio/schemaTypes/postType.ts')
  const config = read('sanity-studio/sanity.config.ts')
  assert.match(settings, /primaryColor/)
  assert.match(settings, /commentsEnabled/)
  assert.match(settings, /membershipEnabled/)
  assert.match(post, /accessLevel/)
  assert.match(post, /seoFields/)
  assert.match(config, /FeatureCenter/)
  assert.match(read('sanity-studio/schemaTypes/redirectType.ts'), /sourcePath/)
  assert.match(read('migrations/0005_engagement_membership.sql'), /analytics_daily/)
  assert.match(read('src/lib/platform.ts'), /TURNSTILE_SECRET_KEY/)
})

test('controlled theme and template center provides safe one-click presets without third-party code execution', () => {
  const center = read('sanity-studio/components/ThemeTemplateCenter.tsx')
  const settings = read('sanity-studio/schemaTypes/siteSettingsType.ts')
  const layout = read('src/app/layout.tsx')
  const home = read('src/app/page.tsx')
  assert.match(center, /经典教程/)
  assert.match(center, /极简蓝白/)
  assert.match(center, /暖色杂志/)
  assert.match(center, /森林知识库/)
  assert.match(center, /安装为新草稿/)
  assert.match(center, /status: 'draft'/)
  assert.match(center, /client\.patch\('site-settings'\)/)
  assert.doesNotMatch(center, /eval\(|new Function|npm install/)
  assert.match(settings, /name: 'themePreset'/)
  assert.match(settings, /name: 'cardStyle'/)
  assert.match(layout, /data-site-theme/)
  assert.match(home, /site-card/)
})

test('template, module, and content-model centers provide reversible no-code operations', () => {
  const themes = read('sanity-studio/components/ThemeTemplateCenter.tsx')
  const features = read('sanity-studio/components/FeatureCenter.tsx')
  const models = read('sanity-studio/components/ContentModelCenter.tsx')
  const settings = read('sanity-studio/schemaTypes/siteSettingsType.ts')
  const article = read('src/app/tutorials/[slug]/page.tsx')
  const config = read('sanity-studio/sanity.config.ts')
  assert.match(themes, /themeBackup/)
  assert.match(themes, /撤销上次更换/)
  assert.match(themes, /cardColumns/)
  assert.match(features, /推荐博客功能包/)
  assert.match(features, /client\.patch\('site-settings'\)/)
  assert.match(models, /分步教程/)
  assert.match(models, /课程章节/)
  assert.match(models, /产品评测/)
  assert.match(models, /常见问题页面/)
  assert.match(config, /ContentModelCenter/)
  assert.match(settings, /shareButtonsEnabled/)
  assert.match(settings, /relatedPostsEnabled/)
  assert.match(article, /ArticleEnhancements/)
  assert.match(article, /相关文章/)
  assert.doesNotMatch(features, /eval\(|new Function|npm install/)
})

test('visual page designer, dynamic fields, and side-by-side template comparison are wired end to end', () => {
  const designer = read('sanity-studio/components/PageDesignerCenter.tsx')
  const fieldDefinition = read('sanity-studio/schemaTypes/customFieldDefinitionType.ts')
  const fieldInput = read('sanity-studio/components/CustomFieldsInput.tsx')
  const comparison = read('sanity-studio/components/TemplateComparisonCenter.tsx')
  const bridge = read('src/components/TemplatePreviewBridge.tsx')
  const content = read('src/lib/sanity-content.ts')
  const visualSections = read('src/components/VisualSections.tsx')
  assert.match(designer, /draggable/)
  assert.match(designer, /onDrop/)
  assert.match(designer, /保存并应用/)
  assert.match(visualSections, /section\.hidden/)
  assert.match(fieldDefinition, /fieldType/)
  assert.match(fieldDefinition, /displayOnPage/)
  assert.match(fieldInput, /customFieldDefinition/)
  assert.match(content, /customFieldsProjection/)
  assert.match(comparison, /当前网站/)
  assert.match(comparison, /候选模板/)
  assert.match(comparison, /iframe/)
  assert.match(bridge, /templatePreview/)
  assert.doesNotMatch(designer + fieldInput + comparison, /eval\(|new Function|dangerouslySetInnerHTML/)
})

test('analytics reporting includes privacy-safe events, protected reports, trends, and CSV export', () => {
  const migration = read('migrations/0006_analytics_reporting.sql')
  const beacon = read('src/components/AnalyticsBeacon.tsx')
  const report = read('src/lib/analytics-report.ts')
  const dashboard = read('src/app/admin/analytics/page.tsx')
  const studio = read('sanity-studio/sanity.config.ts')
  assert.match(migration, /analytics_daily_visitors/)
  assert.match(migration, /analytics_events/)
  assert.doesNotMatch(migration, /raw_ip|ip_address/)
  assert.match(beacon, /page_view/)
  assert.match(beacon, /search/)
  assert.match(beacon, /external_click/)
  assert.match(report, /热门页面/)
  assert.match(report, /reportCsv/)
  assert.match(dashboard, /浏览趋势/)
  assert.match(dashboard, /adminEmail/)
  assert.match(studio, /AnalyticsCenter/)
  assert.match(read('src/app/api/reports/analytics.csv/route.ts'), /text\/csv/)
})

test('legacy admin and account entry points are retired in favor of Sanity Studio', () => {
  const middleware = read('src/middleware.ts')
  assert.match(middleware, /SANITY_STUDIO_URL/)
  assert.match(middleware, /pathname\.startsWith\('\/admin'\)/)
  assert.match(middleware, /pathname === '\/login'/)
  assert.match(middleware, /pathname\.startsWith\('\/api\/admin'\)/)
  assert.match(middleware, /status: 410/)
  assert.doesNotMatch(middleware, /pathname\.startsWith\('\/uploads'\)/)
})

test('Sanity schemas own posts, settings, and image assets', () => {
  const post = read('sanity-studio/schemaTypes/postType.ts')
  const settings = read('sanity-studio/schemaTypes/siteSettingsType.ts')
  assert.match(post, /name: 'coverImage'/)
  assert.match(post, /type: 'image'/)
  assert.match(post, /portableTextField/)
  assert.match(post, /value: 'scheduled'/)
  assert.match(post, /name: 'editorialStage'/)
  assert.match(settings, /name: 'defaultCoverImage'/)
  assert.match(settings, /type: 'image'/)
  assert.match(settings, /name: 'homepageSectionTitle'/)
  assert.match(settings, /name: 'homepageFooterNote'/)
})

test('WordPress-style editing tools include media, preview, scheduling, and review queues', () => {
  const config = read('sanity-studio/sanity.config.ts')
  const structure = read('sanity-studio/structure.ts')
  const portableText = read('sanity-studio/schemaTypes/portableText.ts')
  const publicContent = read('src/lib/sanity-content.ts')
  assert.match(config, /media\(/)
  assert.match(config, /presentationTool/)
  assert.match(config, /SubmitForReviewAction/)
  assert.match(structure, /ContentPreview/)
  assert.match(structure, /待审核/)
  assert.match(structure, /计划发布/)
  assert.match(portableText, /提示框/)
  assert.match(portableText, /操作步骤/)
  assert.match(portableText, /下载按钮/)
  assert.match(publicContent, /status == "scheduled"/)
  assert.match(publicContent, /dateTime\(publishedAt\) <= dateTime\(now\(\)\)/)
  assert.match(publicContent, /expiresAt/)
  assert.match(read('sanity-studio/actions/editorialActions.tsx'), /hasApprovalRole/)
  assert.match(read('src/app/api/draft-mode/enable/route.ts'), /validatePreviewUrl/)
})

test('recovery backups include drafts, published documents, and image binaries', () => {
  const backup = read('scripts/backup-cloudflare.sh')
  assert.match(backup, /export-sanity-content\.mjs/)
  assert.match(backup, /backup-sanity-assets\.mjs/)
  assert.match(read('scripts/backup-sanity-assets.mjs'), /cdn\.sanity\.io/)
  assert.match(read('scripts/backup-sanity-assets.mjs'), /bodyAssets/)
  assert.match(read('scripts/export-sanity-content.mjs'), /perspective', 'raw'/)
  assert.match(read('scripts/export-sanity-content.mjs'), /SANITY_AUTH_TOKEN/)
  assert.match(read('.github/workflows/monthly-cloudflare-backup.yml'), /SANITY_BACKUP_TOKEN/)
})
