'use client'
import { useEffect, useState } from 'react'

type Comment = { id: string; content: string; is_approved: number; created_at: string; post_title?: string; post_slug?: string; author_name?: string; author_email?: string }
const filters = [['pending', '待审核'], ['approved', '已批准'], ['spam', '垃圾评论'], ['trash', '回收站'], ['all', '全部']] as const

export default function CommentsPage() {
  const [items, setItems] = useState<Comment[]>([]); const [selected, setSelected] = useState<string[]>([])
  const [filter, setFilter] = useState('pending'); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const [totals, setTotals] = useState<Record<string, number>>({})
  function load() { setLoading(true); fetch(`/api/admin/comments?status=${filter}&q=${encodeURIComponent(query)}`, { cache: 'no-store' }).then(async r => { const d: any = await r.json(); if (!r.ok) throw new Error(d.error || '加载失败'); setItems(d.comments || []); setTotals(d.totals || {}); setSelected([]) }).catch(e => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(load, [filter])
  async function act(action: string, ids = selected) { if (!ids.length) return; const r = await fetch('/api/admin/comments', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ids, action }) }); if (r.ok) load(); else { const data: any = await r.json().catch(() => ({})); setError(data.error || '操作失败') } }
  const all = items.length > 0 && items.every(item => selected.includes(item.id))
  return <div className="p-8"><div className="mb-6"><h1 className="text-2xl font-bold text-gray-900">评论审核</h1><p className="mt-1 text-sm text-gray-500">批准、退回、标记垃圾评论或移入回收站。</p></div>
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2">{filters.map(([key, label]) => <button key={key} onClick={() => setFilter(key)} className={'rounded-lg border px-3 py-1.5 text-sm ' + (filter === key ? 'border-blue-600 bg-blue-600 text-white' : 'bg-white text-gray-600')}>{label}{key !== 'all' && ` (${Number(totals[key] || 0)})`}</button>)}</div><form onSubmit={e => { e.preventDefault(); load() }} className="flex gap-2"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索评论、作者或文章" className="rounded-lg border px-3 py-2 text-sm"/><button className="rounded-lg border bg-white px-3 py-2 text-sm">搜索</button></form></div>
    {error && <p className="mb-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}
    {selected.length > 0 && <div className="mb-4 flex flex-wrap gap-2 rounded-xl border border-blue-100 bg-blue-50 p-3 text-sm"><span className="mr-2 py-1.5">已选 {selected.length} 条</span><button onClick={() => act('approved')} className="rounded bg-green-600 px-3 py-1.5 text-white">批准</button><button onClick={() => act('pending')} className="rounded border bg-white px-3 py-1.5">设为待审核</button><button onClick={() => act('spam')} className="rounded border bg-white px-3 py-1.5">垃圾评论</button><button onClick={() => act('trash')} className="rounded border bg-white px-3 py-1.5 text-red-600">移入回收站</button></div>}
    <div className="overflow-hidden rounded-2xl border bg-white">{loading ? <div className="py-16 text-center text-gray-400">加载中…</div> : !items.length ? <div className="py-16 text-center text-gray-400">这里没有评论</div> : <table className="w-full text-sm"><thead><tr className="border-b bg-gray-50 text-left text-gray-500"><th className="w-12 px-4 py-3"><input type="checkbox" checked={all} onChange={() => setSelected(all ? [] : items.map(i => i.id))}/></th><th className="px-4 py-3">作者</th><th className="px-4 py-3">评论</th><th className="px-4 py-3">文章</th><th className="px-4 py-3">操作</th></tr></thead><tbody className="divide-y">{items.map(item => <tr key={item.id}><td className="px-4 py-4"><input type="checkbox" checked={selected.includes(item.id)} onChange={() => setSelected(s => s.includes(item.id) ? s.filter(id => id !== item.id) : [...s, item.id])}/></td><td className="px-4 py-4"><p className="font-medium">{item.author_name || '未知用户'}</p><p className="text-xs text-gray-400">{item.author_email}</p></td><td className="max-w-xl px-4 py-4"><p className="whitespace-pre-wrap text-gray-700">{item.content}</p><p className="mt-2 text-xs text-gray-400">{String(item.created_at).replace('T', ' ').slice(0, 16)}</p></td><td className="px-4 py-4">{item.post_slug ? <a className="text-blue-600" href={`/tutorials/${item.post_slug}`} target="_blank">{item.post_title || '查看文章'} ↗</a> : '文章已删除'}</td><td className="px-4 py-4"><div className="flex flex-col items-start gap-2"><button onClick={() => act('approved', [item.id])} className="text-green-700">批准</button><button onClick={() => act('spam', [item.id])} className="text-amber-700">垃圾评论</button><button onClick={() => act('trash', [item.id])} className="text-red-600">回收</button></div></td></tr>)}</tbody></table>}</div>
  </div>
}
