import { defineField, defineType } from 'sanity'
import { pageSectionsField } from './pageSections'

export const siteSettingsType = defineType({
  name: 'siteSettings',
  title: '站点设置',
  type: 'document',
  groups: [
    { name: 'general', title: '基本设置', default: true },
    { name: 'homepage', title: '首页' },
    { name: 'theme', title: '外观' },
    { name: 'seo', title: 'SEO' },
    { name: 'features', title: '功能开关' },
  ],
  fields: [
    defineField({ name: 'siteName', title: '站点名称', type: 'string', group: 'general', validation: rule => rule.required().max(120) }),
    defineField({ name: 'seoDefaultTitle', title: '默认 SEO 标题', type: 'string', group: 'seo', validation: rule => rule.required().max(120) }),
    defineField({ name: 'seoDefaultDescription', title: '默认 SEO 描述', type: 'text', rows: 3, group: 'seo', validation: rule => rule.required().max(180) }),
    defineField({ name: 'seoDefaultOgImage', title: '默认社交分享图片 URL', type: 'url', group: 'seo' }),
    defineField({ name: 'canonicalBaseUrl', title: '网站规范域名', type: 'url', initialValue: 'https://zzgcopilot.com', group: 'seo' }),
    defineField({ name: 'organizationName', title: '组织/作者名称', type: 'string', group: 'seo' }),
    defineField({ name: 'twitterHandle', title: 'X/Twitter 用户名', description: '例如 @zzgcopilot', type: 'string', group: 'seo' }),
    defineField({ name: 'defaultCoverImage', title: '默认文章封面', type: 'image', group: 'general', options: { hotspot: true } }),
    defineField({ name: 'homepageBrandName', title: '首页品牌名称', type: 'string', validation: rule => rule.max(80) }),
    defineField({ name: 'homepageSectionTitle', title: '首页文章区标题', type: 'string', validation: rule => rule.max(80) }),
    defineField({ name: 'homepageSearchPlaceholder', title: '首页搜索框提示文字', type: 'string', validation: rule => rule.max(80) }),
    defineField({ name: 'homepageCtaLabel', title: '首页主按钮文字', type: 'string', validation: rule => rule.max(80) }),
    defineField({ name: 'homepageFooterBrand', title: '首页页脚品牌名称', type: 'string', validation: rule => rule.max(80) }),
    defineField({ name: 'homepageFooterNote', title: '首页页脚说明', type: 'string', validation: rule => rule.max(200) }),
    defineField({ name: 'showDefaultLatestPosts', title: '显示默认“最新教程”卡片区', description: '默认开启，关闭后首页只显示下方添加的可视化首页区块。', type: 'boolean', initialValue: true }),
    pageSectionsField('homepageSections', '首页可视化区块'),
    defineField({ name: 'primaryColor', title: '主色', type: 'color', group: 'theme' }),
    defineField({ name: 'secondaryColor', title: '强调色', type: 'color', group: 'theme' }),
    defineField({ name: 'bodyFont', title: '正文字体', type: 'string', group: 'theme', initialValue: 'system', options: { list: [{ title: '系统字体', value: 'system' }, { title: '无衬线字体', value: 'sans' }, { title: '衬线字体', value: 'serif' }] } }),
    defineField({ name: 'headingFont', title: '标题字体', type: 'string', group: 'theme', initialValue: 'serif', options: { list: [{ title: '衬线字体', value: 'serif' }, { title: '无衬线字体', value: 'sans' }] } }),
    defineField({ name: 'contentWidth', title: '正文最大宽度（像素）', type: 'number', group: 'theme', initialValue: 768, validation: rule => rule.integer().min(600).max(1200) }),
    defineField({ name: 'cardRadius', title: '卡片圆角（像素）', type: 'number', group: 'theme', initialValue: 6, validation: rule => rule.integer().min(0).max(32) }),
    defineField({ name: 'imageQuality', title: '图片质量（1–100）', type: 'number', group: 'theme', initialValue: 82, validation: rule => rule.integer().min(40).max(100) }),
    defineField({ name: 'analyticsEnabled', title: '启用隐私友好访问统计', type: 'boolean', group: 'features', initialValue: false }),
    defineField({ name: 'commentsEnabled', title: '启用文章评论', type: 'boolean', group: 'features', initialValue: false }),
    defineField({ name: 'commentsRequireApproval', title: '评论需要审核', type: 'boolean', group: 'features', initialValue: true, hidden: ({ document }) => !document?.commentsEnabled }),
    defineField({ name: 'contactFormEnabled', title: '启用联系表单', type: 'boolean', group: 'features', initialValue: false }),
    defineField({ name: 'membershipEnabled', title: '启用会员登录', type: 'boolean', group: 'features', initialValue: false }),
    defineField({ name: 'paidContentEnabled', title: '启用付费内容', description: '需要同时配置 Stripe 密钥与 Webhook。', type: 'boolean', group: 'features', initialValue: false }),
    defineField({ name: 'turnstileSiteKey', title: 'Cloudflare Turnstile Site Key', description: '公开站点密钥；Secret Key 必须配置在 Cloudflare 环境变量。', type: 'string', group: 'features' }),
  ],
  preview: { select: { title: 'siteName', subtitle: 'seoDefaultTitle' } },
})
