import { defineField, defineType } from 'sanity'
import { pageSectionsField } from './pageSections'

export const siteSettingsType = defineType({
  name: 'siteSettings',
  title: '站点设置',
  type: 'document',
  groups: [
    { name: 'general', title: '基本设置', default: true },
    { name: 'header', title: '页眉与导航' },
    { name: 'homepage', title: '首页栏目' },
    { name: 'cards', title: '文章卡片' },
    { name: 'footer', title: '页脚' },
    { name: 'theme', title: '颜色与字体' },
    { name: 'seo', title: 'SEO' },
    { name: 'features', title: '功能开关' },
  ],
  fields: [
    defineField({ name: 'siteName', title: '站点名称', type: 'string', group: 'general', validation: rule => rule.required().max(120) }),
    defineField({ name: 'seoDefaultTitle', title: '默认 SEO 标题', type: 'string', group: 'seo', validation: rule => rule.required().max(120) }),
    defineField({ name: 'seoDefaultDescription', title: '默认 SEO 描述', type: 'text', rows: 3, group: 'seo', validation: rule => rule.required().max(180) }),
    defineField({ name: 'seoDefaultOgImage', title: '默认社交分享图片 URL', type: 'url', group: 'seo' }),
    defineField({ name: 'canonicalBaseUrl', title: '网站规范域名', type: 'url', initialValue: 'https://zzgcopilot.com', group: 'seo' }),
    defineField({ name: 'organizationName', title: '组织/作者名称', type: 'string', group: 'seo' }),
    defineField({ name: 'twitterHandle', title: 'X/Twitter 用户名', description: '例如 @zzgcopilot', type: 'string', group: 'seo' }),
    defineField({ name: 'defaultCoverImage', title: '默认文章封面', type: 'image', group: 'general', options: { hotspot: true } }),
    defineField({ name: 'homepageBrandName', title: '网站左上角名称', type: 'string', group: 'header', validation: rule => rule.max(80) }),
    defineField({ name: 'showHeaderSearch', title: '显示顶部搜索框', type: 'boolean', group: 'header', initialValue: true }),
    defineField({ name: 'homepageSearchPlaceholder', title: '搜索框提示文字', type: 'string', group: 'header', validation: rule => rule.max(80), hidden: ({ document }) => document?.showHeaderSearch === false }),
    defineField({ name: 'showHeaderCta', title: '显示顶部主按钮', type: 'boolean', group: 'header', initialValue: true }),
    defineField({ name: 'homepageCtaLabel', title: '顶部主按钮文字', type: 'string', group: 'header', validation: rule => rule.max(80), hidden: ({ document }) => document?.showHeaderCta === false }),
    defineField({ name: 'homepageCtaHref', title: '顶部主按钮链接', description: '留空时自动打开最新一篇教程；也可填写 /pages/about 或完整网址。', type: 'string', group: 'header', validation: rule => rule.max(500), hidden: ({ document }) => document?.showHeaderCta === false }),
    defineField({ name: 'homepageSectionTitle', title: '文章区标题', type: 'string', group: 'homepage', validation: rule => rule.max(80) }),
    defineField({ name: 'homepageIntroText', title: '文章区简介', type: 'text', rows: 2, group: 'homepage', validation: rule => rule.max(240) }),
    defineField({ name: 'showDefaultLatestPosts', title: '显示默认“最新教程”卡片区', description: '默认开启，关闭后首页只显示下方添加的可视化首页区块。', type: 'boolean', group: 'homepage', initialValue: true }),
    defineField({ name: 'postsPerPage', title: '每页显示文章数', type: 'number', group: 'homepage', initialValue: 9, validation: rule => rule.integer().min(3).max(24) }),
    defineField({ name: 'homepageMaxWidth', title: '首页最大宽度（像素）', type: 'number', group: 'homepage', initialValue: 1480, validation: rule => rule.integer().min(960).max(1800) }),
    pageSectionsField('homepageSections', '首页可视化区块', 'homepage'),
    defineField({ name: 'cardColumns', title: '桌面端每行卡片数', type: 'number', group: 'cards', initialValue: 3, options: { list: [{ title: '2 列', value: 2 }, { title: '3 列', value: 3 }, { title: '4 列', value: 4 }] } }),
    defineField({ name: 'cardGap', title: '卡片间距（像素）', type: 'number', group: 'cards', initialValue: 24, validation: rule => rule.integer().min(8).max(48) }),
    defineField({ name: 'cardImageHeight', title: '卡片图片高度（像素）', type: 'number', group: 'cards', initialValue: 150, validation: rule => rule.integer().min(100).max(320) }),
    defineField({ name: 'showCardCategory', title: '显示文章分类', type: 'boolean', group: 'cards', initialValue: true }),
    defineField({ name: 'showCardDate', title: '显示发布日期', type: 'boolean', group: 'cards', initialValue: true }),
    defineField({ name: 'showCardReadingTime', title: '显示阅读时长', type: 'boolean', group: 'cards', initialValue: true }),
    defineField({ name: 'showFooter', title: '显示页脚', type: 'boolean', group: 'footer', initialValue: true }),
    defineField({ name: 'homepageFooterBrand', title: '页脚品牌名称', type: 'string', group: 'footer', validation: rule => rule.max(80), hidden: ({ document }) => document?.showFooter === false }),
    defineField({ name: 'homepageFooterNote', title: '页脚说明', type: 'string', group: 'footer', validation: rule => rule.max(200), hidden: ({ document }) => document?.showFooter === false }),
    defineField({ name: 'primaryColor', title: '主色', type: 'color', group: 'theme' }),
    defineField({ name: 'secondaryColor', title: '强调色', type: 'color', group: 'theme' }),
    defineField({ name: 'headerBackgroundColor', title: '页眉背景色', type: 'color', group: 'theme' }),
    defineField({ name: 'surfaceColor', title: '首页背景色', type: 'color', group: 'theme' }),
    defineField({ name: 'cardBackgroundColor', title: '卡片背景色', type: 'color', group: 'theme' }),
    defineField({ name: 'themePreset', title: '当前主题包', type: 'string', group: 'theme', initialValue: 'classic', options: { list: [{ title: '经典教程', value: 'classic' }, { title: '极简蓝白', value: 'minimal' }, { title: '暖色杂志', value: 'editorial' }, { title: '森林知识库', value: 'forest' }] } }),
    defineField({ name: 'bodyFont', title: '正文字体', type: 'string', group: 'theme', initialValue: 'system', options: { list: [{ title: '系统字体', value: 'system' }, { title: '无衬线字体', value: 'sans' }, { title: '衬线字体', value: 'serif' }] } }),
    defineField({ name: 'headingFont', title: '标题字体', type: 'string', group: 'theme', initialValue: 'serif', options: { list: [{ title: '衬线字体', value: 'serif' }, { title: '无衬线字体', value: 'sans' }] } }),
    defineField({ name: 'contentWidth', title: '正文最大宽度（像素）', type: 'number', group: 'theme', initialValue: 768, validation: rule => rule.integer().min(600).max(1200) }),
    defineField({ name: 'cardRadius', title: '卡片圆角（像素）', type: 'number', group: 'theme', initialValue: 6, validation: rule => rule.integer().min(0).max(32) }),
    defineField({ name: 'cardStyle', title: '卡片样式', type: 'string', group: 'theme', initialValue: 'elevated', options: { list: [{ title: '阴影悬浮', value: 'elevated' }, { title: '简洁边框', value: 'bordered' }, { title: '平面无阴影', value: 'flat' }] } }),
    defineField({ name: 'navigationStyle', title: '导航栏样式', type: 'string', group: 'theme', initialValue: 'sticky', options: { list: [{ title: '滚动时固定', value: 'sticky' }, { title: '普通静态导航', value: 'static' }] } }),
    defineField({ name: 'imageQuality', title: '图片质量（1–100）', type: 'number', group: 'theme', initialValue: 82, validation: rule => rule.integer().min(40).max(100) }),
    defineField({ name: 'analyticsEnabled', title: '启用隐私友好访问统计', type: 'boolean', group: 'features', initialValue: false }),
    defineField({ name: 'commentsEnabled', title: '启用文章评论', type: 'boolean', group: 'features', initialValue: false }),
    defineField({ name: 'commentsRequireApproval', title: '评论需要审核', type: 'boolean', group: 'features', initialValue: true, hidden: ({ document }) => !document?.commentsEnabled }),
    defineField({ name: 'contactFormEnabled', title: '启用联系表单', type: 'boolean', group: 'features', initialValue: false }),
    defineField({ name: 'membershipEnabled', title: '启用会员登录', type: 'boolean', group: 'features', initialValue: false }),
    defineField({ name: 'paidContentEnabled', title: '启用付费内容', description: '需要同时配置 Stripe 密钥与 Webhook。', type: 'boolean', group: 'features', initialValue: false }),
    defineField({ name: 'turnstileSiteKey', title: 'Cloudflare Turnstile Site Key', description: '公开站点密钥；Secret Key 必须配置在 Cloudflare 环境变量。', type: 'string', group: 'features' }),
  ],
  preview: { select: { title: 'siteName', subtitle: 'seoDefaultTitle' } },
})
